name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET for integration testing
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            7.0.306
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - name: Build & Test NExpect
        run: |
          git clone https://github.com/fluffynuts/NExpect
          cd NExpect
          npm ci
          npm install --save-dev zarro@beta
          npm test
          npm run pack
          cd -
      - name: Build & Test Quackers
        run: |
          git clone https://github.com/fluffynuts/quackers
          cd quackers
          npm ci
          npm install --save-dev zarro@beta
          npm test
          npm run pack
          cd -
      - name: Build PeanutButter
        run: |
          git clone https://github.com/PeanutButter
          cd PeanutButter
          npm ci
          npm install --save-dev zarro@beta
          npm run zarro -- build-nuget-packages
          cd -
