name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Test
      env:
        RUNNING_IN_GITHUB_ACTION: 1
        TEST_TIMEOUT: 15000
        MAX_WORKERS: 1
      run: |
        npm ci
        npm test
