name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET for integration testing
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.306

    - name: 🟢 Setup NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: ⬆️ Fetch latest software lists
      run: |
        sudo apt update -q

    - name: 🟥 Setup Redis for test locks
      run: |
        sudo apt install redis-server -q

    - name: Test
      env:
        SUPPRESS_DOWNLOAD_PROGRESS: 1
        RUNNING_IN_GITHUB_ACTION: 1
        TEST_TIMEOUT: 60000
        MAX_WORKERS: 1
      run: |
        npm ci
        npm test
