name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET for integration testing
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.306
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Test
      env:
        SUPPRESS_DOWNLOAD_PROGRESS: 1
        RUNNING_IN_GITHUB_ACTION: 1
        TEST_TIMEOUT: 30000
        MAX_WORKERS: 1
      run: |
        npm ci
        npm test
